### ISSUE TITLE
Análisis de Sensibilidad

### ISSUE THREAD

**Issue by emiliafernanndez** [emiliafernanndez/IO-TPI#7]
Estudiar la variación de la demanda utilizando Monte Carlo

**Comment by salvatigua** [comment]
Tamaño del lote
Variación de la demanda
Para estudiar este último, podríamos hacer Monte Carlo con la demanda. La demanda es aleatoria que sigue distribución normal. Armamos una planilla y hacemos muestreos como si fuera años, con cada temporada. Usamos un tamaño fijo y hallamos CTE para ese muestreo.
Teniendo esto hacemos un histograma de los costos totales y el valor esperado, si hicimos 30 muestreo hacemos 1/30.
También tener en cuenta las restricciones.
